### ISSUE TITLE
TEI to Markdown Conversion broken

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/oxgarage#33] opened 2019-02-03 18:12 UTC
Trying to convert a TEI file (in this case, the basic TEI P5 template in oXygen) to Markdown results in this error:

Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException

I/O error reported by XML parser processing file:/markdown/tei-to-markdown.xsl: /markdown/tei-to-markdown.xsl (No such file or directory)

![screen shot 2019-02-03 at 10 11 19 am](https://user-images.githubusercontent.com/17664763/52180519-1c054680-279c-11e9-8fc6-edc5c2290d6a.png)

**Comment by peterstadler** [comment] 2019-02-03 23:00
I can confirm the issue for both (oxgarage.tei-c.org and oxgarage2.tei-c.org) instances. But I wonder whether this is a newly introduced bug (by the TEI release this week) or whether it never actually worked?

**Comment by jamescummings** [comment] 2019-02-04 14:46
I can confirm that the stylesheet worked and was tested when we first added it to OxGarage, but I've not used it since.

**Comment by hcayless** [comment] 2019-02-04 15:16
The stylesheet appears to work as intended from the command line.

**Comment by peterstadler** [comment] 2019-02-04 15:48
It's just that I can't find any support for a markdown conversion in https://github.com/TEIC/oxgarage/blob/dev/tei-converter/src/main/java/pl/psnc/dl/ege/tei/Format.java nor in https://github.com/TEIC/oxgarage/blob/dev/tei-converter/src/main/java/pl/psnc/dl/ege/tei/TEIConverter.java ?

**Comment by jamescummings** [comment] 2019-02-04 18:06
That certainly seems to be the case. Is the right solution just to add it again. (I *swear* I have a memory to testing this in OxGarage.  Maybe @tuurma can comment since my memory is also she had worked on the XSLT.)

**Comment by hcayless** [comment] 2019-02-04 19:45
I suspect that what's happening is that the file path context is being lost, possibly because the conversion is just using the defaults. I think this may be due to differing defaults between the Saxon XSLT 2.0 and 3.0. I'll try messing with it to see if I can fix it.

**Comment by peterstadler** [comment] 2019-02-05 07:35
thanks @hcayless !

**Comment by peterstadler** [comment] 2019-08-09 14:36
is fixed by #37 and deployed at http://oxgarage.tei-c.org/, closing here

**Closed by peterstadler** 2019-08-09 14:36 UTC
Labels: bug
