### ISSUE TITLE
conversion error of P4 TEI perseus xml file to docbook

### ISSUE THREAD

**Issue by androclus** [TEIC/oxgarage#9] opened 2017-06-20 18:09 UTC
_[Note: This may just be a duplicate of [Issue 2](https://github.com/TEIC/oxgarage/issues/2), although there are 2 differences: 1) In my case, I am using the installation at tei-c.org, not a local installation.  2) I do not have problems converting to all other formats, just the DocBook format. I am for instance able to convert my .xml file to epub, .odt, and .rtf without error.]_

Hi, I am trying to use [tei-c.org/oxgarage](http://www.tei-c.org/oxgarage/#) to convert a TEI XML document that came from perseus at tufts(1).  I _think_ the file is a P4 TEI doc.  I am trying to convert it to DocBook, using the [oxgarage page](http://www.tei-c.org/oxgarage/#).

I will doc. the whole process I went through, so you get a feel for all the steps I went through where there could be additional user interface improvement, should anyone there want to address any of those issues.  But  the main hold-up is that I get an error in a pink box (2) which says..

> Error occured. Please check the filetype and try again.?
> Error: class pl.psnc.dl.ege.exception.ConverterException
> Failed to compile stylesheet. 1 error detected.

..and this error does not provide me with enough information as an end-user to know what to do next, or with an action I can take to move the process forward.

(My main questions are at the bottom.)

So I click on the blue ? in the pink area at the end of that first line, and it pops up a help message (3).

The Help/Error message dialog box suggests that I check the format of my document is selected correctly, (and I had checked, "TEI P4 XML Document").  But it does not provide any tools for helping me verify that I have chosen the right format, nor does the page upload seem to validate the document by itself.  I hope I have picked the right format.

Inspecting the XML file I see only "TEI.2" but that does not match anything in the choices given on the OxGarage page. I see nothing on the main page of tei (tei-c.org) which I can see which leads to "formats", so I Google, and it takes me to http://www.tei-c.org/Vault/P4/doc/html/ref-TEI2.html but this page also does not indicate that "TEI.2" has anything to do with the "P4" or "P5" choices, etc.  But the url _does_ contain a 'P4' in it, so I go with that (for now).

Having tentatively resolved the file format is P4, I decide I still need to figure out whether this particular Perseus document is valid, but I see no tools for doing so.

I do Google again, for "tei validate", and i find a site, [TBE Validation Service](http://teibyexample.org/xquery/TBEvalidator.xq) which I _hope_ will be helpful.  Uploading the same file to that site, I only get an error message, "The content of element 'body' is not complete.".  Uploading the P5-converted version, I just get the same error message.  So I give up for now and return to oxgarage.

Next, I try just converting to P5 (using OxGarage), which converts without error (yay!)

So then again, I save that P5 version as another .xml file, and then try to re-upload it and convert again to DocBook.  But I get the same error with no help as to exactly what about the file it does not like, and where.

The Help/error screen (3) does tell me to check if my document is corrupt but again does not provide any link or tools or suggestions for doing so. Eyeballing it, it seems fine (but of course it would help me to debug the file by myself if there were a validator for these input files (such as for HTML, at validator.w3.org), but I don't see any).

Lastly, the error/help window indicates to "contact us", but does not provide a link.  So I close the error window and (back on the main screen (2) just scroll to the bottom looking for a "Contact Us" link, and I see a "feedback" link.  So I click on that, which pops me here into submitting an issue on github.

- Q1) Is there anything I am doing wrong?  Maybe it's just something obvious I'm missing? (..been known to happen.. :P )
- Q2) How can I validate the original P4 (if that is indeed what it is) file?
- Q3) How can I get more information out of the oxgarage interface -- information which would help me to know what to do next (what line is problematic or what tag, etc. it expects to see, or what character (and position) is outside of the parser's legal syntax, etc.)?

Let me know if there's anything I've forgotten to supply or any other info you need from me.

Thanks! -JS

(1) Go to [the start page for the doc at perseus](http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0170%3Atext%3DPhaedo) and click on "An [XML version](http://www.perseus.tufts.edu/hopper/dltext?doc=Perseus%3Atext%3A1999.01.0170) of this text is available...".

(2) screenshot 1

![oxgarage](https://user-images.githubusercontent.com/221629/27348474-09f13114-55a9-11e7-9a48-dc73bb8a13b1.png)

(3) screenshot 2

![oxgarage2](https://user-images.githubusercontent.com/221629/27348482-10c585bc-55a9-11e7-9c55-11d8c194d0f2.png)

**Comment by peterstadler** [comment] 2017-11-05 18:45
Yes, I can confirm the issue and am able to reproduce on my local test machine. The error I see is 
```
Error at xsl:import on line 11 column 44 
  XTSE0165: I/O error reported by XML parser processing file:/var/lib/common/verbatim.xsl:
  /var/lib/common/verbatim.xsl (No such file or directory)
```
stemming from `stylesheet/docbook/teitodocbook.xsl`. But the import statement looks ok and it works outside OxGarage. Maybe @jamescummings has an idea what's happening here?

BTW, this does not look related to #2 but seems to be a peculiarity of the docbook transformation.

**Comment by timber8020** [comment] 2019-08-06 06:00
> Yes, I can confirm the issue and am able to reproduce on my local test machine. The error I see is
> 
> ```
> Error at xsl:import on line 11 column 44 
>   XTSE0165: I/O error reported by XML parser processing file:/var/lib/common/verbatim.xsl:
>   /var/lib/common/verbatim.xsl (No such file or directory)
> ```
> 
> stemming from `stylesheet/docbook/teitodocbook.xsl`. But the import statement looks ok and it works outside OxGarage. Maybe @jamescummings has an idea what's happening here?
> 
> BTW, this does not look related to #2 but seems to be a peculiarity of the docbook transformation.

@peterstadler , @jamescummings 
dear sir
it still happens in my case. I run it by docker container , the docker image that I pulled is "teic/oxgarage"

The error displays like that:
"Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException

I/O error reported by XML parser processing file:/usr/local/common/verbatim.xsl: /usr/local/common/verbatim.xsl (No such file or directory)"

**Comment by timber8020** [comment] 2019-08-06 06:02
> > Yes, I can confirm the issue and am able to reproduce on my local test machine. The error I see is
> > ```
> > Error at xsl:import on line 11 column 44 
> >   XTSE0165: I/O error reported by XML parser processing file:/var/lib/common/verbatim.xsl:
> >   /var/lib/common/verbatim.xsl (No such file or directory)
> > ```
> > 
> > 
> > stemming from `stylesheet/docbook/teitodocbook.xsl`. But the import statement looks ok and it works outside OxGarage. Maybe @jamescummings has an idea what's happening here?
> > BTW, this does not look related to #2 but seems to be a peculiarity of the docbook transformation.
> 
> @peterstadler , @jamescummings
> dear sir
> it still happens in my case. I run it by docker container , the docker image that I pulled is "teic/oxgarage"
> 
> The error displays like that:
> "Error occured. Please check the filetype and try again.?
> Error: class pl.psnc.dl.ege.exception.ConverterException
> 
> I/O error reported by XML parser processing file:/usr/local/common/verbatim.xsl: /usr/local/common/verbatim.xsl (No such file or directory)"

It happens when I browser a ms word(.docx) to convert to docbook.

**Comment by peterstadler** [comment] 2019-08-08 13:53
I think I found a fix, see PR #37. DockerHub should have a working image soon at `teic/oxgarage:issue9` so we can test it thoroughly.  Any feedback welcome :)

**Comment by timber8020** [comment] 2019-08-09 01:24
> I think I found a fix, see PR #37. DockerHub should have a working image soon at `teic/oxgarage:issue9` so we can test it thoroughly. Any feedback welcome :)

1.
The error disappear and the result file can be downloaded well in docker image version issue9, It can convert docx to docbook.
But the error still exits in version latest. sorry , I can't get what it means in different version.

2.
There is another error that i find in version issue9 when I convert docx to epub, the error displays: 
"Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException
Failed to read input file". 
Maybe it happens in latest version too.

3. In docker image version  issue9, if the docx has a flow chat such as rectangle，arrows  ,  when converted to a docbook, it can't be converted well with the flow chart. In the docbook result file, the flow chat element is that:
<para>
      <emphasis role="ERROR">�</emphasis>
      <emphasis role="docxError">unable to handle picture here, no embed or link</emphasis>
   </para>
.
What should I do to make the flow chat to be converted correctly?
Similarly , how to get the image files in docx when it converted to docbook?  Is there some problems that I understand the features of oxgrage project?

thanks.

**Comment by timber8020** [comment] 2019-08-09 01:28
> I think I found a fix, see PR #37. DockerHub should have a working image soon at `teic/oxgarage:issue9` so we can test it thoroughly. Any feedback welcome :)

@peterstadler

1>
The error disappear and the result file can be downloaded well in docker image version issue9, It can convert docx to docbook.
But the error still exits in version latest. sorry , I can't get what it means in different version.

2>
There is another error that i find in version issue9 when I convert docx to epub, the error displays:
"Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException
Failed to read input file".
Maybe it happens in latest version too.

3>
In docker image version issue9, if the docx has a flow chat such as rectangle，arrows , when converted to a docbook, it can't be converted well with the flow chart. In the docbook result file, the flow chat element is that:
`Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException

Failed to read input file`.
 What should I do to make the flow chat to be converted correctly? Similarly , how to get the image files in docx when it converted to docbook? Is there some problems that I understand the features of oxgrage project?

thanks.

**Comment by timber8020** [comment] 2019-08-09 01:31
> I think I found a fix, see PR #37. DockerHub should have a working image soon at `teic/oxgarage:issue9` so we can test it thoroughly. Any feedback welcome :)

@peterstadler

1>
The error disappear and the result file can be downloaded well in docker image version issue9, It can convert docx to docbook.
But the error still exits in version latest. sorry , I can't get what it means in different version.

2>
There is another error that i find in version issue9 when I convert docx to epub, the error displays:
"Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException
Failed to read input file".
Maybe it happens in latest version too.

3>
In docker image version issue9, if the docx has a flow chat such as rectangle，arrows , when converted to a docbook, it can't be converted well with the flow chart. In the docbook result file, the flow chat element is that:
`<para>
      <emphasis role="ERROR">�</emphasis>
      <emphasis role="docxError">unable to handle picture here, no embed or link</emphasis>
   </para>.`
What should I do to make the flow chat to be converted correctly? Similarly , how to get the image files in docx when it converted to docbook? Is there some problems that I understand the features of oxgrage project?

thanks.

**Comment by peterstadler** [comment] 2019-08-09 07:45
> 1>
> The error disappear and the result file can be downloaded well in docker image version issue9, It can convert docx to docbook.
> But the error still exits in version latest. sorry , I can't get what it means in different version.

The fix is only applied in the `issue9` branch on GitHub and the respective Docker image built from that branch. Only when that branch is merged into dev and subsequently into master, the latest Docker image will be updated ("latest" in Docker terminology equals "master" in Git terminology).

> 2>
> There is another error that i find in version issue9 when I convert docx to epub, the error displays:
> "Error occured. Please check the filetype and try again.?
> Error: class pl.psnc.dl.ege.exception.ConverterException
> Failed to read input file".
> Maybe it happens in latest version too.

Could you please check whether it occurs on current OxGarage at http://oxgarage.tei-c.org as well? If so, please check the issues whether there is already something related or open a new one -- since it does not seem to be related to this one.

> 3>
> In docker image version issue9, if the docx has a flow chat such as rectangle，arrows , when converted to a docbook, it can't be converted well with the flow chart. In the docbook result file, the flow chat element is that:
> `<para> <emphasis role="ERROR">�</emphasis> <emphasis role="docxError">unable to handle picture here, no embed or link</emphasis> </para>.`
> What should I do to make the flow chat to be converted correctly? Similarly , how to get the image files in docx when it converted to docbook? Is there some problems that I understand the features of oxgrage project?

Could you check without OxGarage, i.e. running this transformation from the command line or via Oxygen to see whether it stems from the TEI Stylesheets rather than OxGarage? (Or send me the file so I will check)

**Closed** 2019-08-09 12:32 UTC
Labels: bug

**Comment by timber8020** [comment] 2019-08-12 00:57
Sorry, I don't kwow the way without OxGarage. Here is the docx file.

[cmf003.docx](https://github.com/TEIC/oxgarage/files/3490628/cmf003.docx)

**Comment by peterstadler** [comment] 2019-08-12 08:57
Thanks for the test file!

Indeed, the ePub transformation (your second point) seems to be broken due to a [Stylesheets issue](https://github.com/TEIC/Stylesheets/issues/312).

Your last point is yet another deficiency in the docx2tei transformation. I will raise a ticket in the Stylesheets repo.
