### ISSUE TITLE
error while converting from pptx to pdf

### ISSUE THREAD

**Issue by sabineseifert** [TEIC/oxgarage#11] opened 2017-07-05 15:52 UTC
error message is: 

"Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException
could not load document: input.pptx"

but trying again doesn't help. no spaces or other unallowed characters in my file name.

**Comment by peterstadler** [comment] 2017-11-05 10:38
Hi @sabineseifert,

I can confirm your issue for the current version of OxGarage running at http://www.tei-c.org/oxgarage/  but I can't reproduce on my local test version. We will need to do more testing but then replace the official version.

It's probably late but just to let you know … ;)

**Comment by peterstadler** [comment] 2018-04-04 11:58
Just tested:

* http://www.tei-c.org/ege-webclient/ still produces the error "Error occured. Please check the filetype and try again.?"
* https://oxgarage-paderborn.tei-c.org/ works fine but produces an empty file (as is to be expected from the underlying Stylesheets)

Since the second OxGarage is running the dev version (of OxGarage; TEI sources and Stylesheets are identical), my hope is that this issue can be closed with the next proper release of OxGarage (and when the software is deployed to the main server). 

see #12 for more or less the same issue and remedy …

**Comment by peterstadler** [comment] 2018-11-06 21:14
Just tested the current oxgarage version (with two pptx files) and the Issue seems to be fixed. Closing now, but feel free to reopen when the error pops up again!

**Closed by peterstadler** 2018-11-06 21:14 UTC
