### ISSUE TITLE
TEI to csv conversion gives error

### ISSUE THREAD

**Issue by chopinesque** [TEIC/oxgarage#12] opened 2017-08-17 07:59 UTC
Error occured. Please check the filetype and try again.?
Error: class pl.psnc.dl.ege.exception.ConverterException

Error during conversion unzipping : probably wrong input data.

**Comment by martindholmes** [comment] 2017-08-17 17:40
Could you provide your input TEI file?

**Comment by chopinesque** [comment] 2017-08-18 05:13
[wiktionary_ru-el_2017-07-31.zip](https://github.com/TEIC/oxgarage/files/1233358/wiktionary_ru-el_2017-07-31.zip)

**Comment by martindholmes** [comment] 2017-08-18 15:12
The TEI Oxygen plugin doesn't have a TEI-to-CSV conversion, does it?

**Comment by martindholmes** [comment] 2017-08-18 15:14
If you run the teitocsv conversion in the Stylesheets/bin folder at the command line, there's no error, but you get an empty file, because that input is (I assume) expecting to convert a TEI table rather than a dictionary.

**Comment by sydb** [comment] 2017-08-19 00:16
Indeed, `Stylesheets/profiles/default/csv/to.xsl` (the underlying stylesheet used by `Stylesheets/bin/teitocsv`) looks only for `<table>` elements. Cleverly, it can deal with more than one, but “All other content is discarded”.

However, this isn’t particularly hard to do (if you know XSLT). Here is one demo of how to do this. I don’t claim this is the best way to do this, or that it even produces the output you want (because, after all, you have some entries with multiple senses, and some senses with multiple definitions — how should they be handled?), but it does seem to do what I would expect.

~~~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:tei="http://www.tei-c.org/ns/1.0"
  xpath-default-namespace="http://www.tei-c.org/ns/1.0"
  xmlns:tmp="https://github.com/chopinesque"
  version="2.0">
  
  <!-- Written 2017-08-18 by Syd Bauman for chopinesque -->
  <!-- Copyleft -->
  
  <xsl:output method="text"/>
  <xsl:variable name="quot">"</xsl:variable>
  
  <xsl:template match="/">
    <xsl:text>entry #, sense #, orth, def&#x0A;</xsl:text>
    <xsl:apply-templates select="/TEI/text/body/entry/sense"/>
  </xsl:template>
  
  <xsl:template match="sense">
    <xsl:value-of select="count( preceding::entry )+1"/>
    <xsl:text>,</xsl:text>
    <xsl:value-of select="count( preceding-sibling::sense )+1"/>
    <xsl:text>,</xsl:text>
    <xsl:value-of select="tmp:csvout( ../form/orth )"/>
    <xsl:text>,</xsl:text>
    <xsl:for-each select="def">
      <xsl:value-of select="tmp:csvout( . )"/>
      <xsl:value-of select="if ( position() eq last() ) then '' else ','"/>
    </xsl:for-each>
    <xsl:text>&#x0A;</xsl:text>
  </xsl:template>
  
  <xsl:function name="tmp:csvout">
    <xsl:param name="value"/>
    <xsl:choose>
      <xsl:when test="contains( $value, ',' )">
        <xsl:value-of select='concat( $quot, $value, $quot )'/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$value"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:function>
  
</xsl:stylesheet>
~~~~~

**Comment by chopinesque** [comment] 2017-08-23 06:27
Thanks! Not sure how to run this on a Windows machine (I had tested through the web app).

**Comment by martindholmes** [comment] 2017-08-23 16:47
I have never actually used the web version of Oxygen Author, so I don't know how it works. Is there a TEI-to-CSV conversion in there? If so, it must have been added by the Oxygen folks, so perhaps this is an issue to ask about on the Oxygen forum.

**Comment by peterstadler** [comment] 2017-11-05 19:00
Getting back to the original error:
I can confirm the original error still exists with the OxGarage live version. Regrettably, on my local OxGarage version this is not the case, making it hard to debug.

**Comment by martindholmes** [comment] 2017-11-05 19:04
Does the live version have the TEI packages installed, and are they perhaps older versions?

**Comment by peterstadler** [comment] 2017-11-05 19:48
AFAIK, OxGarage is running inside Tomcat but should be picking up the TEI schemas and stylesheets from `/usr/share`. And `/usr/share/xml/tei/odd/VERSION` tells me it's "3.2.0", `/usr/share/xml/tei/stylesheet/VERSION` is "7.42.0".

**Comment by peterstadler** [comment] 2018-04-04 11:55
Just tested:

* http://www.tei-c.org/ege-webclient/ still produces the error "Error occured. Please check the filetype and try again.?"
* https://oxgarage-paderborn.tei-c.org/ works fine but produces an empty file (as is to be expected from the underlying Stylesheets)

Since the second OxGarage is running the dev version (of OxGarage; TEI sources and Stylesheets are identical), my hope is that this issue can be closed with the next proper release of OxGarage (and when the software is deployed to the main server).

**Comment by peterstadler** [comment] 2018-11-06 21:20
Just tested again with the current OxGarage version and the issue seems to be fixed. NB, only the OxGarage error "Please check the filetype and try again" is fixed; the result is an empty document due to the Stylesheets issue @sydb [explained](https://github.com/TEIC/oxgarage/issues/12#issuecomment-323486779).
Closing here, but feel free to open a [Stylesheets issue](https://github.com/TEIC/Stylesheets/issues).

**Closed by peterstadler** 2018-11-06 21:20 UTC
